//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_detalle_ingreso
    {
        public int id { get; set; }
        public int fk_id_doc_cabecera_ingreso { get; set; }
        public int fk_id_producto { get; set; }
        public int cantidad { get; set; }
        public double costo { get; set; }
    
        public virtual Doc_cabecera_ingreso Doc_cabecera_ingreso { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
