//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_cabecera_egreso : IEntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_cabecera_egreso()
        {
            this.Doc_detalle_egreso = new HashSet<Doc_detalle_egreso>();
        }
    
        public int id { get; set; }
        public int fk_id_tipo_doc { get; set; }
        public int fk_id_cliente { get; set; }
        public string letra { get; set; }
        public int sucursal { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tipo_documento Tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_detalle_egreso> Doc_detalle_egreso { get; set; }
    }
}
