//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_producto : IEntityBase
    {
        public int id { get; set; }
        public int fk_id_producto { get; set; }
        public int antes { get; set; }
        public int movimiento { get; set; }
        public int despues { get; set; }
        public int fk_id_tipo_mov_prod { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Tipo_movimiento_prod Tipo_movimiento_prod { get; set; }
    }
}
