//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_documento()
        {
            this.Doc_cabecera_egreso = new HashSet<Doc_cabecera_egreso>();
            this.Doc_cabecera_ingreso = new HashSet<Doc_cabecera_ingreso>();
        }
    
        public int id { get; set; }
        public string tipo_documento { get; set; }
        public string letra { get; set; }
        public int sucursal { get; set; }
        public int numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_cabecera_egreso> Doc_cabecera_egreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_cabecera_ingreso> Doc_cabecera_ingreso { get; set; }
    }
}
