//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using Entities.EntidadesDigitoVerificador;
    using System;
    using System.Collections.Generic;
    
    public partial class Producto :IEntityDV
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int fk_id_categoria { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> profundidad { get; set; }
        public string codigo { get; set; }
        public byte[] DVH { get; set; }
    }
}
